// <auto-generated />
namespace fiskaltrust.Middleware.Storage.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DailyClosingNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DailyClosingNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111357337_DailyClosingNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
