using fiskaltrust.ifPOS.v2;
using fiskaltrust.Middleware.Contracts.Repositories;
using fiskaltrust.Middleware.Localization.QueuePT.Logic;
using fiskaltrust.Middleware.Localization.v2.Helpers;
using fiskaltrust.Middleware.Localization.v2.Validation;
using fiskaltrust.Middleware.Localization.v2.Validation.Rules.Global;
using fiskaltrust.storage.V0;
using FluentValidation;
using FluentValidation.Results;
using Moq;
using Xunit;
using Xunit.Abstractions;

namespace fiskaltrust.Middleware.Localization.v2.UnitTest.Validation.E2E;

/// <summary>
/// E2E tests demonstrating error messages output.
/// These tests show how FluentValidation generates error messages.
/// </summary>
public class ErrorMessagesE2ETests
{
    private readonly ITestOutputHelper _output;

    public ErrorMessagesE2ETests(ITestOutputHelper output)
    {
        _output = output;
    }

    private static FVReceiptReferenceProvider CreateMockProvider()
    {
        var mockRepo = new Mock<IMiddlewareQueueItemRepository>();
        mockRepo.Setup(x => x.GetEntriesOnOrAfterTimeStampAsync(It.IsAny<long>(), It.IsAny<int?>()))
            .Returns(AsyncEnumerable.Empty<ftQueueItem>());
        mockRepo.Setup(x => x.GetByReceiptReferenceAsync(It.IsAny<string>(), null))
            .Returns(AsyncEnumerable.Empty<ftQueueItem>());
        mockRepo.Setup(x => x.GetLastQueueItemAsync())
            .ReturnsAsync((ftQueueItem?)null);
        return new FVReceiptReferenceProvider(
            new AsyncLazy<IMiddlewareQueueItemRepository>(() => Task.FromResult(mockRepo.Object)));
    }

    private static QueuePT.ValidationFV.ReceiptValidator CreatePTValidator()
    {
        var provider = CreateMockProvider();
        var repo = new AsyncLazy<IMiddlewareQueueItemRepository>(() =>
        {
            var mockRepo = new Mock<IMiddlewareQueueItemRepository>();
            mockRepo.Setup(x => x.GetEntriesOnOrAfterTimeStampAsync(It.IsAny<long>(), It.IsAny<int?>()))
                .Returns(AsyncEnumerable.Empty<ftQueueItem>());
            mockRepo.Setup(x => x.GetLastQueueItemAsync())
                .ReturnsAsync((ftQueueItem?)null);
            return Task.FromResult(mockRepo.Object);
        });
        return new QueuePT.ValidationFV.ReceiptValidator(
            provider,
            new DocumentStatusProvider(repo),
            new VoidValidator(repo),
            new RefundValidator(repo));
    }

    #region Auto-Generated Messages (Raw FluentValidation)

    [Fact]
    public void AutoGenerated_NotEmpty_ShowsDefaultMessage()
    {
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "",
                    VATRate = 23.0m,
                    Amount = 10.00m
                }
            }
        };

        var result = validator.Validate(request);

        _output.WriteLine("TEST: Auto-Generated NotEmpty Message");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "NotEmptyValidator");
    }

    [Fact]
    public void AutoGenerated_GreaterThanOrEqual_ShowsDefaultMessage()
    {
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "Test",
                    VATRate = -5.0m,
                    Amount = 10.00m
                }
            }
        };

        var result = validator.Validate(request);

        _output.WriteLine("TEST: Auto-Generated GreaterThanOrEqualTo Message");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "GreaterThanOrEqualValidator");
    }

    [Fact]
    public void AutoGenerated_NotEqual_ShowsDefaultMessage()
    {
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "Test",
                    VATRate = 23.0m,
                    Amount = 0m
                }
            }
        };

        var result = validator.Validate(request);

        _output.WriteLine("TEST: Auto-Generated NotEqual Message");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "NotEqualValidator");
    }

    [Fact]
    public async Task AutoGenerated_MinimumLength_ShowsDefaultMessage()
    {
        var validator = CreatePTValidator();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "AB",
                    VATRate = 23.0m,
                    Amount = 10.00m
                }
            }
        };

        var result = await validator.ValidateAsync(request);

        _output.WriteLine("TEST: Auto-Generated MinimumLength Message (PT Market)");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "MinimumLengthValidator");
    }

    [Fact]
    public void AutoGenerated_MultipleErrors_ShowsAllMessages()
    {
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "",
                    VATRate = -1m,
                    Amount = 0m
                }
            }
        };

        var result = validator.Validate(request);

        _output.WriteLine("TEST: Multiple Auto-Generated Errors");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Equal(3, result.Errors.Count);
    }

    #endregion

    #region Custom Override Messages

    [Fact]
    public async Task CustomOverride_SumMismatch_ShowsCustomMessage()
    {
        var validator = new ReceiptValidations(CreateMockProvider());
        var request = new ReceiptRequest
        {
            cbReceiptAmount = 100.00m,
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem { Description = "Product 1", VATRate = 23.0m, Amount = 10.00m },
                new ChargeItem { Description = "Product 2", VATRate = 23.0m, Amount = 15.00m }
            }
        };

        var result = await validator.ValidateAsync(request);

        _output.WriteLine("TEST: Custom Override - Sum Mismatch Message");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
        Assert.Contains(result.Errors, e => e.ErrorMessage.Contains("25") && e.ErrorMessage.Contains("100"));
    }

    #endregion

    #region Comparison: Raw vs Custom

    [Fact]
    public async Task Comparison_RawPredicateValidator_VsCustomMessage()
    {
        _output.WriteLine("COMPARISON: Raw .Must() vs Custom .Must()");

        var request = new ReceiptRequest
        {
            cbReceiptAmount = 100.00m,
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem { Description = "Product", VATRate = 23.0m, Amount = 25.00m }
            }
        };

        // RAW (without custom message)
        var rawValidator = new RawMustValidator();
        var rawResult = rawValidator.Validate(request);

        _output.WriteLine("RAW .Must() - No custom message:");
        PrintErrors(rawResult);

        // CUSTOM (with override)
        var customValidator = new ReceiptValidations(CreateMockProvider());
        var customResult = await customValidator.ValidateAsync(request);

        _output.WriteLine("CUSTOM .Must() - With WithMessage() and WithErrorCode():");
        PrintErrors(customResult);

        Assert.False(rawResult.IsValid);
        Assert.False(customResult.IsValid);

        Assert.Contains(rawResult.Errors, e => e.ErrorCode == "PredicateValidator");
        Assert.Contains(customResult.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
    }

    private class RawMustValidator : AbstractValidator<ReceiptRequest>
    {
        public RawMustValidator()
        {
            RuleFor(x => x.cbReceiptAmount)
                .Must((request, receiptAmount) =>
                {
                    if (!receiptAmount.HasValue) return true;
                    if (request.cbChargeItems == null || !request.cbChargeItems.Any()) return true;
                    var sum = request.cbChargeItems.Sum(item => item.Amount);
                    return sum == receiptAmount.Value;
                })
                .When(x => x.cbReceiptAmount.HasValue);
        }
    }

    #endregion

    #region Full E2E Market Validation

    [Fact]
    public async Task E2E_PTMarket_AllRules_ShowsAllMessages()
    {
        var validator = CreatePTValidator();
        var request = new ReceiptRequest
        {
            cbReceiptAmount = 50.00m,
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "AB",
                    VATRate = 23.0m,
                    Amount = 10.00m
                }
            }
        };

        var result = await validator.ValidateAsync(request);

        _output.WriteLine("E2E TEST: PT Market - All Rules Combined");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.True(result.Errors.Count >= 2);
        Assert.Contains(result.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
        Assert.Contains(result.Errors, e => e.ErrorCode == "MinimumLengthValidator");
    }

    [Fact]
    public async Task E2E_ESMarket_AllRules_ShowsAllMessages()
    {
        var validator = new QueueES.ValidationFV.ReceiptValidator(CreateMockProvider());
        var request = new ReceiptRequest
        {
            cbReceiptAmount = 50.00m,
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "AB",
                    VATRate = 21.0m,
                    Amount = 10.00m,
                    VATAmount = null
                }
            }
        };

        var result = await validator.ValidateAsync(request);

        _output.WriteLine("E2E TEST: ES Market - All Rules Combined");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.True(result.Errors.Count >= 2);
        Assert.Contains(result.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
        Assert.Contains(result.Errors, e => e.ErrorCode == "NotNullValidator");
    }

    #endregion

    #region Helper Methods

    private void PrintErrors(ValidationResult result)
    {
        if (result.IsValid)
        {
            _output.WriteLine("VALID - No errors");
            return;
        }

        _output.WriteLine($"INVALID - {result.Errors.Count} error(s):");
        foreach (var error in result.Errors)
        {
            _output.WriteLine($"  [{error.ErrorCode}] {error.PropertyName}: {error.ErrorMessage}");
        }
        _output.WriteLine("");
    }

    #endregion
}
