using fiskaltrust.ifPOS.v2;
using fiskaltrust.Middleware.Localization.QueuePT.ValidationFV;
using fiskaltrust.Middleware.Localization.v2.Validation.Rules.Global;
using FluentValidation;
using FluentValidation.Results;
using Xunit;
using Xunit.Abstractions;

namespace fiskaltrust.Middleware.Localization.v2.UnitTest.Validation.E2E;

/// <summary>
/// E2E tests demonstrating error messages output.
/// These tests show how FluentValidation generates error messages.
/// </summary>
public class ErrorMessagesE2ETests
{
    private readonly ITestOutputHelper _output;

    public ErrorMessagesE2ETests(ITestOutputHelper output)
    {
        _output = output;
    }

    #region Auto-Generated Messages (Raw FluentValidation)

    [Fact]
    public void AutoGenerated_NotEmpty_ShowsDefaultMessage()
    {
        // Arrange
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "",  // Empty - violates NotEmpty()
                    VATRate = 23.0m,
                    Amount = 10.00m
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("TEST: Auto-Generated NotEmpty Message");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request: Description = \"\" (empty)");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "NotEmptyValidator");
    }

    [Fact]
    public void AutoGenerated_GreaterThanOrEqual_ShowsDefaultMessage()
    {
        // Arrange
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "Test",
                    VATRate = -5.0m,  // Negative - violates GreaterThanOrEqualTo(0)
                    Amount = 10.00m
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("TEST: Auto-Generated GreaterThanOrEqualTo Message");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request: VATRate = -5.0 (negative, should be >= 0)");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "GreaterThanOrEqualValidator");
    }

    [Fact]
    public void AutoGenerated_NotEqual_ShowsDefaultMessage()
    {
        // Arrange
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "Test",
                    VATRate = 23.0m,
                    Amount = 0m  // Zero - violates NotEqual(0)
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("TEST: Auto-Generated NotEqual Message");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request: Amount = 0 (should not be 0)");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "NotEqualValidator");
    }

    [Fact]
    public void AutoGenerated_MinimumLength_ShowsDefaultMessage()
    {
        // Arrange - Using PT validator which has MinimumLength(3) rule
        var validator = new ReceiptValidator();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "AB",  // 2 chars - PT requires 3+
                    VATRate = 23.0m,
                    Amount = 10.00m
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("TEST: Auto-Generated MinimumLength Message (PT Market)");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request: Description = \"AB\" (2 chars, PT requires 3+)");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "MinimumLengthValidator");
    }

    [Fact]
    public void AutoGenerated_MultipleErrors_ShowsAllMessages()
    {
        // Arrange
        var validator = new ChargeItemValidations();
        var request = new ReceiptRequest
        {
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "",     // Error 1: NotEmpty
                    VATRate = -1m,        // Error 2: GreaterThanOrEqualTo
                    Amount = 0m           // Error 3: NotEqual
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("TEST: Multiple Auto-Generated Errors");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request: Description = \"\", VATRate = -1, Amount = 0");
        _output.WriteLine("         (All three fields invalid)");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Equal(3, result.Errors.Count);
    }

    #endregion

    #region Custom Override Messages

    [Fact]
    public void CustomOverride_SumMismatch_ShowsCustomMessage()
    {
        // Arrange
        var validator = new ReceiptValidations();
        var request = new ReceiptRequest
        {
            cbReceiptAmount = 100.00m,  // Expected total
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem { Description = "Product 1", VATRate = 23.0m, Amount = 10.00m },
                new ChargeItem { Description = "Product 2", VATRate = 23.0m, Amount = 15.00m }
                // Sum = 25, but cbReceiptAmount = 100
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("TEST: Custom Override - Sum Mismatch Message");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request: cbReceiptAmount = 100.00");
        _output.WriteLine("         ChargeItems: 10.00 + 15.00 = 25.00");
        _output.WriteLine("         (Sum doesn't match!)");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Contains(result.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
        Assert.Contains(result.Errors, e => e.ErrorMessage.Contains("25") && e.ErrorMessage.Contains("100"));
    }

    #endregion

    #region Comparison: Raw vs Custom

    [Fact]
    public void Comparison_RawPredicateValidator_VsCustomMessage()
    {
        // This test demonstrates the difference between using .Must()
        // with default message vs custom message

        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("COMPARISON: Raw .Must() vs Custom .Must()");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");

        var request = new ReceiptRequest
        {
            cbReceiptAmount = 100.00m,
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem { Description = "Product", VATRate = 23.0m, Amount = 25.00m }
            }
        };

        // --- RAW (without custom message) ---
        var rawValidator = new RawMustValidator();
        var rawResult = rawValidator.Validate(request);

        _output.WriteLine("──────────────────────────────────────────────────────────────");
        _output.WriteLine("RAW .Must() - No custom message:");
        _output.WriteLine("──────────────────────────────────────────────────────────────");
        PrintErrors(rawResult);
        _output.WriteLine("");

        // --- CUSTOM (with override) ---
        var customValidator = new ReceiptValidations();
        var customResult = customValidator.Validate(request);

        _output.WriteLine("──────────────────────────────────────────────────────────────");
        _output.WriteLine("CUSTOM .Must() - With WithMessage() and WithErrorCode():");
        _output.WriteLine("──────────────────────────────────────────────────────────────");
        PrintErrors(customResult);

        // Both should fail
        Assert.False(rawResult.IsValid);
        Assert.False(customResult.IsValid);

        // But with different error codes
        Assert.Contains(rawResult.Errors, e => e.ErrorCode == "PredicateValidator");
        Assert.Contains(customResult.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
    }

    /// <summary>
    /// Raw validator without custom message - for comparison
    /// </summary>
    private class RawMustValidator : AbstractValidator<ReceiptRequest>
    {
        public RawMustValidator()
        {
            RuleFor(x => x.cbReceiptAmount)
                .Must((request, receiptAmount) =>
                {
                    if (!receiptAmount.HasValue) return true;
                    if (request.cbChargeItems == null || !request.cbChargeItems.Any()) return true;
                    var sum = request.cbChargeItems.Sum(item => item.Amount);
                    return sum == receiptAmount.Value;
                })
                .When(x => x.cbReceiptAmount.HasValue);
            // NO .WithMessage() or .WithErrorCode() - uses defaults
        }
    }

    #endregion

    #region Full E2E Market Validation

    [Fact]
    public void E2E_PTMarket_AllRules_ShowsAllMessages()
    {
        // Arrange - PT market validator (Global + PT rules)
        var validator = new ReceiptValidator();
        var request = new ReceiptRequest
        {
            cbReceiptAmount = 50.00m,  // Wrong - items sum to 10
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "AB",   // Too short for PT (needs 3+)
                    VATRate = 23.0m,
                    Amount = 10.00m
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("E2E TEST: PT Market - All Rules Combined");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request:");
        _output.WriteLine("  cbReceiptAmount = 50.00");
        _output.WriteLine("  ChargeItems[0]:");
        _output.WriteLine("    Description = \"AB\" (2 chars)");
        _output.WriteLine("    VATRate = 23.0");
        _output.WriteLine("    Amount = 10.00");
        _output.WriteLine("");
        _output.WriteLine("Expected errors:");
        _output.WriteLine("  1. [Global] Sum mismatch: 10.00 ≠ 50.00");
        _output.WriteLine("  2. [PT] Description too short: 2 chars < 3 chars");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Equal(2, result.Errors.Count);
        Assert.Contains(result.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
        Assert.Contains(result.Errors, e => e.ErrorCode == "MinimumLengthValidator");
    }

    [Fact]
    public void E2E_ESMarket_AllRules_ShowsAllMessages()
    {
        // Arrange - ES market validator (Global + ES rules)
        var validator = new fiskaltrust.Middleware.Localization.QueueES.ValidationFV.ReceiptValidator();
        var request = new ReceiptRequest
        {
            cbReceiptAmount = 50.00m,  // Wrong - items sum to 10
            cbChargeItems = new List<ChargeItem>
            {
                new ChargeItem
                {
                    Description = "AB",   // OK for ES (no min length rule)
                    VATRate = 21.0m,
                    Amount = 10.00m,
                    VATAmount = null      // Missing - ES requires VATAmount
                }
            }
        };

        // Act
        var result = validator.Validate(request);

        // Assert & Output
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("E2E TEST: ES Market - All Rules Combined");
        _output.WriteLine("═══════════════════════════════════════════════════════════════");
        _output.WriteLine("");
        _output.WriteLine("Request:");
        _output.WriteLine("  cbReceiptAmount = 50.00");
        _output.WriteLine("  ChargeItems[0]:");
        _output.WriteLine("    Description = \"AB\" (OK for ES, no min length)");
        _output.WriteLine("    VATRate = 21.0");
        _output.WriteLine("    Amount = 10.00");
        _output.WriteLine("    VATAmount = null (ES requires this!)");
        _output.WriteLine("");
        _output.WriteLine("Expected errors:");
        _output.WriteLine("  1. [Global] Sum mismatch: 10.00 ≠ 50.00");
        _output.WriteLine("  2. [ES] VATAmount is required");
        _output.WriteLine("");
        PrintErrors(result);

        Assert.False(result.IsValid);
        Assert.Equal(2, result.Errors.Count);
        Assert.Contains(result.Errors, e => e.ErrorCode == "ChargeItemsSumMismatch");
        Assert.Contains(result.Errors, e => e.ErrorCode == "NotNullValidator");
    }

    #endregion

    #region Helper Methods

    private void PrintErrors(ValidationResult result)
    {
        if (result.IsValid)
        {
            _output.WriteLine("✅ VALID - No errors");
            return;
        }

        _output.WriteLine($"❌ INVALID - {result.Errors.Count} error(s):");
        _output.WriteLine("");

        foreach (var error in result.Errors)
        {
            _output.WriteLine($"  [{error.ErrorCode}] {error.PropertyName}");
            _output.WriteLine($"    → {error.ErrorMessage}");
            if (error.AttemptedValue != null)
            {
                _output.WriteLine($"    Attempted value: {error.AttemptedValue}");
            }
            _output.WriteLine("");
        }
    }

    #endregion
}
