#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource", IsApplication=true)]

namespace fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.coordinatorLayoutStyle = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Essentials.Resource.Attribute.font = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.keylines = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.keylines;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchor = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.layout_anchor;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchorGravity = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Attribute.layout_behavior = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.layout_behavior;
			global::Xamarin.Essentials.Resource.Attribute.layout_dodgeInsetEdges = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Attribute.layout_insetEdge = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Essentials.Resource.Attribute.layout_keyline = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.layout_keyline;
			global::Xamarin.Essentials.Resource.Attribute.statusBarBackground = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.statusBarBackground;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.accessibility_action_clickable_span = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_action_clickable_span;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_0 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_0;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_1 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_1;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_10 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_10;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_11 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_11;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_12 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_12;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_13 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_13;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_14 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_14;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_15 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_15;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_16 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_16;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_17 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_17;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_18 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_18;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_19 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_19;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_2 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_2;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_20 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_20;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_21 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_21;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_22 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_22;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_23 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_23;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_24 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_24;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_25 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_25;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_26 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_26;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_27 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_27;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_28 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_28;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_29 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_29;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_3 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_3;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_30 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_30;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_31 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_31;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_4 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_4;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_5 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_5;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_6 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_6;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_7 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_7;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_8 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_8;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_9 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.accessibility_custom_action_9;
			global::Xamarin.Essentials.Resource.Id.actions = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.all = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.all;
			global::Xamarin.Essentials.Resource.Id.async = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.bottom = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.bottom;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.center = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.center;
			global::Xamarin.Essentials.Resource.Id.center_horizontal = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.center_horizontal;
			global::Xamarin.Essentials.Resource.Id.center_vertical = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.center_vertical;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.clip_horizontal = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.clip_horizontal;
			global::Xamarin.Essentials.Resource.Id.clip_vertical = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.clip_vertical;
			global::Xamarin.Essentials.Resource.Id.dialog_button = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.dialog_button;
			global::Xamarin.Essentials.Resource.Id.end = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.end;
			global::Xamarin.Essentials.Resource.Id.fill = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.fill;
			global::Xamarin.Essentials.Resource.Id.fill_horizontal = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.fill_horizontal;
			global::Xamarin.Essentials.Resource.Id.fill_vertical = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.fill_vertical;
			global::Xamarin.Essentials.Resource.Id.forever = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.left = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.left;
			global::Xamarin.Essentials.Resource.Id.line1 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.right;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.start = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.start;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_actions = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_accessibility_actions;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_clickable_spans = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_accessibility_clickable_spans;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_heading = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_accessibility_heading;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_pane_title = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_accessibility_pane_title;
			global::Xamarin.Essentials.Resource.Id.tag_screen_reader_focusable = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_screen_reader_focusable;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.top = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Id.top;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.custom_dialog = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.custom_dialog;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Style.Widget_Support_CoordinatorLayout = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_keylines = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColorItem_android_offset;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::fiskaltrust.Middleware.Queue.Sqlite.AndriodLauncherTest.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fragment_fast_out_extra_slow_in = 2130771968;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7F020000
			public const int fragment_close_enter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fragment_close_exit = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int fragment_fade_enter = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fragment_fade_exit = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fragment_open_enter = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fragment_open_exit = 2130837509;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F030000
			public const int alpha = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int coordinatorLayoutStyle = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int font = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int fontProviderAuthority = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int fontProviderCerts = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int fontProviderFetchStrategy = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int fontProviderFetchTimeout = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int fontProviderPackage = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int fontProviderQuery = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int fontProviderSystemFontFamily = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int fontStyle = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int fontVariationSettings = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int fontWeight = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int keylines = 2130903053;
			
			// aapt resource value: 0x7F03000F
			public const int layout_anchor = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int layout_anchorGravity = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int layout_behavior = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int layout_dodgeInsetEdges = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int layout_insetEdge = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int layout_keyline = 2130903060;
			
			// aapt resource value: 0x7F03000E
			public const int lStar = 2130903054;
			
			// aapt resource value: 0x7F030015
			public const int nestedScrollViewStyle = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int queryPatterns = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int shortcutMatchRequired = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int statusBarBackground = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int ttcIndex = 2130903065;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F040000
			public const int androidx_core_ripple_material_light = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int androidx_core_secondary_text_default_material_light = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int browser_actions_bg_grey = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int browser_actions_divider_color = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int browser_actions_text_color = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int browser_actions_title_color = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int call_notification_answer_color = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int call_notification_decline_color = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int colorAccent = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int colorPrimary = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int colorPrimaryDark = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int ic_launcher_background = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_action_color_filter = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_icon_bg_color = 2130968589;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int browser_actions_context_menu_max_width = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int browser_actions_context_menu_min_padding = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int compat_button_inset_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int compat_button_inset_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int compat_button_padding_horizontal_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int compat_button_padding_vertical_material = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int compat_control_corner_material = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int compat_notification_large_icon_max_height = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int compat_notification_large_icon_max_width = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int fab_margin = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_action_icon_size = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_action_text_size = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_big_circle_margin = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_content_margin_start = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notification_large_icon_height = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int notification_large_icon_width = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int notification_main_column_padding_top = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notification_media_narrow_margin = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int notification_right_icon_size = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_right_side_padding_top = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int notification_small_icon_background_padding = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int notification_small_icon_size_as_large = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int notification_subtext_size = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int notification_top_pad = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int notification_top_pad_large_text = 2131034136;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int abc_vector_test = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int ic_call_answer = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int ic_call_answer_low = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int ic_call_answer_video = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int ic_call_answer_video_low = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int ic_call_decline = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int ic_call_decline_low = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int notification_action_background = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int notification_bg = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int notification_bg_low = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int notification_bg_low_normal = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int notification_bg_low_pressed = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int notification_bg_normal = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int notification_bg_normal_pressed = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int notification_icon_background = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int notification_oversize_large_icon_bg = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int notification_template_icon_bg = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int notification_template_icon_low_bg = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int notification_tile_bg = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int notify_panel_notification_icon_bg = 2131099667;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public const int accessibility_action_clickable_span = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int accessibility_custom_action_0 = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int accessibility_custom_action_1 = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int accessibility_custom_action_10 = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int accessibility_custom_action_11 = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int accessibility_custom_action_12 = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int accessibility_custom_action_13 = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int accessibility_custom_action_14 = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int accessibility_custom_action_15 = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int accessibility_custom_action_16 = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int accessibility_custom_action_17 = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int accessibility_custom_action_18 = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int accessibility_custom_action_19 = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int accessibility_custom_action_2 = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int accessibility_custom_action_20 = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int accessibility_custom_action_21 = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int accessibility_custom_action_22 = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int accessibility_custom_action_23 = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int accessibility_custom_action_24 = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int accessibility_custom_action_25 = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int accessibility_custom_action_26 = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int accessibility_custom_action_27 = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int accessibility_custom_action_28 = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int accessibility_custom_action_29 = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int accessibility_custom_action_3 = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int accessibility_custom_action_30 = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int accessibility_custom_action_31 = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int accessibility_custom_action_4 = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int accessibility_custom_action_5 = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int accessibility_custom_action_6 = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int accessibility_custom_action_7 = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int accessibility_custom_action_8 = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int accessibility_custom_action_9 = 2131165216;
			
			// aapt resource value: 0x7F070025
			public const int actions = 2131165221;
			
			// aapt resource value: 0x7F070021
			public const int action_container = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int action_divider = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int action_image = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int action_text = 2131165220;
			
			// aapt resource value: 0x7F070026
			public const int all = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int async = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int blocking = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int bottom = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int browser_actions_header_text = 2131165226;
			
			// aapt resource value: 0x7F07002D
			public const int browser_actions_menu_items = 2131165229;
			
			// aapt resource value: 0x7F07002B
			public const int browser_actions_menu_item_icon = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int browser_actions_menu_item_text = 2131165228;
			
			// aapt resource value: 0x7F07002E
			public const int browser_actions_menu_view = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int center = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int center_horizontal = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int center_vertical = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int chronometer = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int clip_horizontal = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int clip_vertical = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int dialog_button = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int edit_text_id = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int end = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int fill = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int fill_horizontal = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int fill_vertical = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int forever = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int fragment_container_view_tag = 2131165244;
			
			// aapt resource value: 0x7F07003D
			public const int hide_ime_id = 2131165245;
			
			// aapt resource value: 0x7F07003E
			public const int icon = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int icon_group = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int info = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int italic = 2131165249;
			
			// aapt resource value: 0x7F070042
			public const int left = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int line1 = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int line3 = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int none = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int normal = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int notification_background = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int notification_main_column = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int notification_main_column_container = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int report_drawn = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int right = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int right_icon = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int right_side = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int special_effects_controller_view_tag = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int start = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int tag_accessibility_actions = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int tag_accessibility_clickable_spans = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int tag_accessibility_heading = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int tag_accessibility_pane_title = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int tag_on_apply_window_listener = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int tag_on_receive_content_listener = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int tag_on_receive_content_mime_types = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int tag_screen_reader_focusable = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int tag_state_description = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int tag_transition_group = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int tag_unhandled_key_event_manager = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int tag_unhandled_key_listeners = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int tag_window_insets_animation_callback = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int text = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int text2 = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int time = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int title = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int top = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int view_tree_lifecycle_owner = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int view_tree_on_back_pressed_dispatcher_owner = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int view_tree_saved_state_registry_owner = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int view_tree_view_model_store_owner = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int visible_removing_fragment_view_tag = 2131165286;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public const int status_bar_notification_info_maxnum = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090000
			public const int activity_main = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int browser_actions_context_menu_page = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int browser_actions_context_menu_row = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int custom_dialog = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int ime_base_split_test_activity = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int ime_secondary_split_test_activity = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int notification_action = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int notification_action_tombstone = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int notification_template_custom_big = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int notification_template_icon_group = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int notification_template_part_chronometer = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int notification_template_part_time = 2131296267;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F0A0000
			public const int ic_launcher = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int ic_launcher_foreground = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int ic_launcher_round = 2131361794;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0B0000
			public const int action_settings = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int androidx_startup = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int app_name = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int call_notification_answer_action = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int call_notification_answer_video_action = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int call_notification_decline_action = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int call_notification_hang_up_action = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int call_notification_incoming_text = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int call_notification_ongoing_text = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int call_notification_screening_text = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int status_bar_notification_info_overflow = 2131427338;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0C0000
			public const int TextAppearance_Compat_Notification = 2131492864;
			
			// aapt resource value: 0x7F0C0001
			public const int TextAppearance_Compat_Notification_Info = 2131492865;
			
			// aapt resource value: 0x7F0C0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131492866;
			
			// aapt resource value: 0x7F0C0003
			public const int TextAppearance_Compat_Notification_Time = 2131492867;
			
			// aapt resource value: 0x7F0C0004
			public const int TextAppearance_Compat_Notification_Title = 2131492868;
			
			// aapt resource value: 0x7F0C0005
			public const int Widget_Compat_NotificationActionContainer = 2131492869;
			
			// aapt resource value: 0x7F0C0006
			public const int Widget_Compat_NotificationActionText = 2131492870;
			
			// aapt resource value: 0x7F0C0007
			public const int Widget_Support_CoordinatorLayout = 2131492871;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x101011C,0x1010194,0x1010195,0x1010196,0x101030C,0x101030D }
			public static int[] AnimatedStateListDrawableCompat = new int[] {
					16843036,
					16843156,
					16843157,
					16843158,
					16843532,
					16843533};
			
			// aapt resource value: 3
			public const int AnimatedStateListDrawableCompat_android_constantSize = 3;
			
			// aapt resource value: 0
			public const int AnimatedStateListDrawableCompat_android_dither = 0;
			
			// aapt resource value: 4
			public const int AnimatedStateListDrawableCompat_android_enterFadeDuration = 4;
			
			// aapt resource value: 5
			public const int AnimatedStateListDrawableCompat_android_exitFadeDuration = 5;
			
			// aapt resource value: 2
			public const int AnimatedStateListDrawableCompat_android_variablePadding = 2;
			
			// aapt resource value: 1
			public const int AnimatedStateListDrawableCompat_android_visible = 1;
			
			// aapt resource value: { 0x10100D0,0x1010199 }
			public static int[] AnimatedStateListDrawableItem = new int[] {
					16842960,
					16843161};
			
			// aapt resource value: 1
			public const int AnimatedStateListDrawableItem_android_drawable = 1;
			
			// aapt resource value: 0
			public const int AnimatedStateListDrawableItem_android_id = 0;
			
			// aapt resource value: { 0x1010199,0x1010449,0x101044A,0x101044B }
			public static int[] AnimatedStateListDrawableTransition = new int[] {
					16843161,
					16843849,
					16843850,
					16843851};
			
			// aapt resource value: 0
			public const int AnimatedStateListDrawableTransition_android_drawable = 0;
			
			// aapt resource value: 2
			public const int AnimatedStateListDrawableTransition_android_fromId = 2;
			
			// aapt resource value: 3
			public const int AnimatedStateListDrawableTransition_android_reversible = 3;
			
			// aapt resource value: 1
			public const int AnimatedStateListDrawableTransition_android_toId = 1;
			
			// aapt resource value: { 0x7F030016,0x7F030017 }
			public static int[] Capability = new int[] {
					2130903062,
					2130903063};
			
			// aapt resource value: 0
			public const int Capability_queryPatterns = 0;
			
			// aapt resource value: 1
			public const int Capability_shortcutMatchRequired = 1;
			
			// aapt resource value: { 0x10101A5,0x101031F,0x1010647,0x7F030000,0x7F03000E }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					16844359,
					2130903040,
					2130903054};
			
			// aapt resource value: 3
			public const int ColorStateListItem_alpha = 3;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: 2
			public const int ColorStateListItem_android_lStar = 2;
			
			// aapt resource value: 4
			public const int ColorStateListItem_lStar = 4;
			
			// aapt resource value: { 0x7F03000D,0x7F030018 }
			public static int[] CoordinatorLayout = new int[] {
					2130903053,
					2130903064};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F03000F,0x7F030010,0x7F030011,0x7F030012,0x7F030013,0x7F030014 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130903055,
					2130903056,
					2130903057,
					2130903058,
					2130903059,
					2130903060};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F030003,0x7F030004,0x7F030005,0x7F030006,0x7F030007,0x7F030008,0x7F030009 }
			public static int[] FontFamily = new int[] {
					2130903043,
					2130903044,
					2130903045,
					2130903046,
					2130903047,
					2130903048,
					2130903049};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F030002,0x7F03000A,0x7F03000B,0x7F03000C,0x7F030019 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130903042,
					2130903050,
					2130903051,
					2130903052,
					2130903065};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: 6
			public const int FontFamily_fontProviderSystemFontFamily = 6;
			
			// aapt resource value: { 0x1010003,0x10100D0,0x10100D1 }
			public static int[] Fragment = new int[] {
					16842755,
					16842960,
					16842961};
			
			// aapt resource value: { 0x1010003,0x10100D1 }
			public static int[] FragmentContainerView = new int[] {
					16842755,
					16842961};
			
			// aapt resource value: 0
			public const int FragmentContainerView_android_name = 0;
			
			// aapt resource value: 1
			public const int FragmentContainerView_android_tag = 1;
			
			// aapt resource value: 1
			public const int Fragment_android_id = 1;
			
			// aapt resource value: 0
			public const int Fragment_android_name = 0;
			
			// aapt resource value: 2
			public const int Fragment_android_tag = 2;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			// aapt resource value: { 0x101011C,0x1010194,0x1010195,0x1010196,0x101030C,0x101030D }
			public static int[] StateListDrawable = new int[] {
					16843036,
					16843156,
					16843157,
					16843158,
					16843532,
					16843533};
			
			// aapt resource value: { 0x1010199 }
			public static int[] StateListDrawableItem = new int[] {
					16843161};
			
			// aapt resource value: 0
			public const int StateListDrawableItem_android_drawable = 0;
			
			// aapt resource value: 3
			public const int StateListDrawable_android_constantSize = 3;
			
			// aapt resource value: 0
			public const int StateListDrawable_android_dither = 0;
			
			// aapt resource value: 4
			public const int StateListDrawable_android_enterFadeDuration = 4;
			
			// aapt resource value: 5
			public const int StateListDrawable_android_exitFadeDuration = 5;
			
			// aapt resource value: 2
			public const int StateListDrawable_android_variablePadding = 2;
			
			// aapt resource value: 1
			public const int StateListDrawable_android_visible = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0E0000
			public const int xamarin_essentials_fileprovider_file_paths = 2131623936;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
