using System.Runtime.Serialization;

namespace fiskaltrust.ifPOS.v1.me
{
    [DataContract]
    public class ComputeIICResponse
    {
        /// <summary>
        /// Unique invoice code (also called 'IKOF'), calculated from the invoice data and signed with the PosOperator's private key.
        /// </summary>
        /// <remarks>
        /// MD5 hash of the signature that is created from the invoice data and the PosOperator's private key. 
        /// This value is generated by the SCU and also passed to the central invoice register (CIS) service. 
        /// It can further be used to reference this invoice, e.g. in case of corrections or cancellations.
        /// </remarks>
        [DataMember(Order = 10)]
        public string IIC { get; set; }

        /// <summary>
        /// Signature, calculated from the invoice data and signed with the PosOperator's private key.
        /// </summary>
        [DataMember(Order = 20)]
        public string IICSignature { get; set; }
    }
}
