name: "Sign"
inputs:
  path:
    required: true
    type: string
  filter:
    required: true
    type: string
  azureKeyVaultUrl:
    required: true
    type: string
  azureKeyVaultCertificate:
    required: true
    type: string
  azureKeyVaultClientId:
    required: true
    type: string
  azureKeyVaultTenantId:
    required: true
    type: string
  azureKeyVaultClientSecret:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: dotnet tool install --global AzureSignTool
      name: Install AzureSignTool
      shell: pwsh

    - run: |
        Get-ChildItem -Path "${{ inputs.path }}" -Filter "${{ inputs.filter }}" -Recurse | ForEach-Object {
          azuresigntool sign `
          --azure-key-vault-url "${{ inputs.azureKeyVaultUrl }}" `
          --azure-key-vault-certificate "${{ inputs.azureKeyVaultCertificate }}" `
          --azure-key-vault-client-id "${{ inputs.azureKeyVaultClientId }}" `
          --azure-key-vault-tenant-id "${{ inputs.azureKeyVaultTenantId }}" `
          --azure-key-vault-client-secret "${{ inputs.azureKeyVaultClientSecret }}" `
          $_.FullName
        }
      name: Sign files
      shell: pwsh
