namespace fiskaltrust.Middleware.SCU.DE.CryptoVision.Models
{
    public enum SeResult
    {
        ExecutionOk = 0,

        ErrorMissingParameter = 0x1000,
        ErrorFunctionNotSupported,
        ErrorAllocationfailed,
        ErrorFileNotFound,
        ErrorSECommunicationFailed,
        ErrorTSECommandDataInvalid,
        ErrorTSEResponseDataInvalid,
        ErrorTSEUnknownError,
        ErrorStreamWrite,
        ErrorIO,
        ErrorTSETimeout,
        ErrorBufferTooSmall,
        ErrorCallback,
        ErrorTSEFirmwareVersion,
        ErrorTransport,
        ErrorNoStartup,
        ErrorNoStorage,

        ErrorAuthenticationFailed = 0x2000,
        ErrorUnblockFailed,

        ErrorRetrieveLogMessageFailed = 0x3000,
        ErrorStorageFailure,
        ErrorUpdateTimeFailed,
        ErrorParameterMismatch,
        ErrorIdNotFound,
        ErrorNoSuchKey,
        ErrorERSalreadyMapped,
        ErrorNoERS,
        ErrorNoKey,
        ErrorTransactionNumberNotFound,
        ErrorNoDataAvailable,
        ErrorTooManyRecords,
        ErrorStartTransactionFailed,
        ErrorUpdateTransactionFailed,
        ErrorFinishTransactionFailed,
        ErrorRestoreFailed,
        ErrorStoringInitDataFailed,
        ErrorExportCertFailed,
        ErrorNoLogMessage,
        ErrorReadingLogMessage,
        ErrorNoTransaction,
        ErrorSeApiNotInitialized,
        ErrorSeApiDeactivated,
        ErrorSeApiNotDeactivated,
        ErrorTimeNotSet,
        ErrorCertificateExpired,
        ErrorSecureElementDisabled,
        ErrorUserNotAuthorized,
        ErrorUserNotAuthenticated,
        ErrorDescriptionNotSetByManufacturer,
        ErrorDescriptionSetByManufacturer,
        ErrorExportSerialNumbersFailed,
        ErrorGetMaxNumberOfClientsFailed,
        ErrorGetCurrentNumberOfClientsFailed,
        ErrorGetMaxNumberTransactionsFailed,
        ErrorGetCurrentNumberOfTransactionsFailed,
        ErrorGetSupportedUpdateVariantsFailed,
        ErrorDeleteStoredDataFailed,
        ErrorUnexportedStoredData,
        ErrorSigningSystemOperationDataFailed,
        ErrorUserIdNotManaged,
        ErrorUserIdNotAuthenticated,
        ErrorDisableSecureElementFailed,
        ErrorClassSD = 0x4000,
        ErrorUnknown = 0xFFFF
    }
}