namespace fiskaltrust.Middleware.Localization.QueuePT.UnitTest.Certification;

public static class PTCertificationTestCasesPhase2
{
    public static List<BusinessCase> Cases =
    [
        new BusinessCase("T6", "Create a simplified invoice (Article 40 of CIVA) for a customer who only provided their VAT number (with no other identification information in the database either from previous or subsequent document issuance) and corresponding PDF", true, PT_Phase2_CertificationExamples.Case_T6()),
        // T7 Is not supported
        // new BusinessCase("T7", "Create an invoice (Article 36 of CIVA) and then cancel it (if the application allows it), with the cancellation being the responsibility of a user different from the one who created the document. If it is possible to print a cancelled document, generate the corresponding PDF that visibly shows that the document is cancelled", false, null),
        new BusinessCase("T8", "If the application allows it, create a document that can be delivered to the customer to verify the transfer of goods or provision of services (order, table consultation, verification document, etc.) and corresponding PDF", true, PT_Phase2_CertificationExamples.Case_T8()),
        // T9 is not supported
        // new BusinessCase("T9", "If the application allows it, create a transport document issued under the Goods in Circulation Regime (delivery note, transport note, etc.) and corresponding PDF in 4 copies (quadruplicate)", false, null),
        // T10 is not applicable
        new BusinessCase("T10", "Create an invoice relating to one of the documents in points 9 and 10 (must generate the OrderReferences element) with a date 2 days later and by a user different from those who created the original documents. If the invoice relates to the document in point 9, consider that the goods/services were made available to the acquirer on the date of that document (attention to filling in the TaxPointDate field of the invoice)", true, PT_Phase2_CertificationExamples.Case_T10()),
        new BusinessCase("T11", "Create a credit note based on that invoice (must generate the References element). If you did not comply with the previous point, you should create a credit note on another document", true, PT_Phase2_CertificationExamples.Case_T11(), "T10"),
        // T12 is not supported
        // new BusinessCase("T12", "If the application allows credit sales, create an invoice whose due date is different from the document date (must generate the PaymentTerms element) and corresponding PDF", false, null),
        new BusinessCase("T13", "Create an invoice in the Cash VAT Regime (or another document, if the program does not issue invoices) with 5 lines with the following characteristics (display the PDF). The exemption reasons for the 2nd line and 5th line must be different. This document must be issued under these conditions, even if the program does not issue invoices in the Cash VAT Regime: 1st line: 1 unit, Product, €12, 6% tax rate; 2nd line: 1 unit, Product, €10, 0% tax rate (must generate TaxExemptionReason element); 3rd line: 1 unit, Product, €10, 13% tax rate; 4th line: 1 unit, Service, €10, 23% tax rate; 5th line: 1 unit, Product, €10, 0% tax rate (must generate TaxExemptionReason element)", true, PT_Phase2_CertificationExamples.Case_T13()),
        // T14 is not supported
        // new BusinessCase("T14", "If the application allows it, create an invoice-receipt and corresponding PDF", false, null),
        // T15 is not supported
        // new BusinessCase("T15", "If the application allows it, create a partial credit note relating to the invoice from the previous point where the unit price of the 1st line is corrected by €2.00 and the return of the product unit from the 3rd line occurred. Create the corresponding PDF", false, null),
        new BusinessCase("T16", "Create a document with 2 non-exempt product/service lines (with quantities greater than 1): the 1st line must contain 100 units of product, unit price (UnitPrice) of €0.55 and a discount of 8.8%. The second line must contain 3.5 units (or 4 if decimal values are not allowed) with unit price (UnitPrice) of €3.45. A global discount of 10% must also be granted to the document, if the application allows it, and corresponding PDF (must generate the SettlementAmount element). Note: in document lines, the UnitPrice field must be without tax and reflect line discounts and global discounts (header)", true, PT_Phase2_CertificationExamples.Case_T16()),
        new BusinessCase("T17", "Create an invoice whose payment was recorded in the application (if the application allows it) - must generate structure 4.1.4.20.6 Payment", true, PT_Phase2_CertificationExamples.Case_T17(), "T16"),
        // T18 is not supported
        // new BusinessCase("T18", "If the application allows it, create a document (with non-exempt lines if the application allows it), in foreign currency and corresponding PDF", false, null),
        new BusinessCase("T19", "Create a document (with non-exempt lines if the application allows it) whose GrossTotal is less than €1.00 but greater than 0.00 and corresponding PDF. If the application allows, use an identified customer (name) who makes a purchase for the 1st time and therefore without a customer record, but who has not provided the VAT number (use VAT number 999999990)", true, PT_Phase2_CertificationExamples.Case_T19()),
        new BusinessCase("T20", "Create a document for an identified customer (name) who also makes a purchase for the 1st time, different from the previous one, but who also did not indicate the VAT number (use VAT number 999999990) and corresponding PDF", true, PT_Phase2_CertificationExamples.Case_T20()),
        new BusinessCase("T21", "Create a document with 2000 units of a non-exempt product or service with a low unit price, if possible, create in the application with 0.001", true, PT_Phase2_CertificationExamples.Case_T21()),
        new BusinessCase("T22", "Create an invoice whose SystemEntryDate is before 10 AM", true, PT_Phase2_CertificationExamples.Case_T22()),
        new BusinessCase("T23", "Create a document that occupies 2 pages of invoice lines, in printing and corresponding PDF (see 2.2.11 of Dispatch 8632/2014)", false, null),
        // T24 is not supported
        // new BusinessCase("T24", "If the program allows it, a corrective invoice document is requested (debit or credit note) that corrects only tax (must generate the TaxBase field)", false, null),
        // T25 is not supported
        // new BusinessCase("T25", "If the program allows it, create a document with 2 identical products with their respective serial numbers and corresponding PDF (must generate the SerialNumber field)", false, null),
        // T26 is not supported
        // new BusinessCase("T26", "If the program allows it, create a document where the electronic administrative document e-DA issued under Article 36 of CIEC is recorded (must generate the ARCNo field)", false, null),
        // T27 is not supported
        // new BusinessCase("T27", "If the program allows it, create a document where the IEC (Special Consumption Tax) is evidenced by the introduction into consumption of goods subject to these taxes (must generate the IECAmount field or a line with \"Product\" of type (ProductType) \"E\")", false, null),
        // T28 is not supported
        // new BusinessCase("T28", "Simulate the integration of 2 manual documents according to point 2.4 of Dispatch No. 8632/2014 of July 3 of the Director General of the Tax and Customs Authority where the 1st document belongs to series F with No. 23 from 14-01-2022 and the 2nd belongs to series D with No. 3 from 12-01-2022 and corresponding PDF. (Note that, according to point 2.4.2, a new document of the same type must be created that collects all elements of the manual document issued, meaning that all elements are free entry, for example: usual denomination, quantity, price, tax value, total tax and document, etc.)", true, PT_Phase2_CertificationExamples.Case_T28()),
        // T29 is not supported
        // new BusinessCase("T29", "Simulate the integration of 2 documents (from 30-01-2022) according to point 2.5 of Dispatch No. 8632/2014 of July 3 of the Director General of the Tax and Customs Authority, through their duplicates (printed, in physical file or electronic file), of documents non-existent in the data repository due to backup restoration due to system anomaly. Consider that the document date (InvoiceDate) to be restored is not equal to the registration date (SystemEntryDate). Note that in this series the InvoiceDate is from the original document that may not coincide with the system date at the time the recovery is performed", false, null),
        // T30 is not supported
        // new BusinessCase("T30", "Simulate the integration of 2 documents (from 30-01-2022) according to point 2.3 of Dispatch No. 8632/2014 of July 3 of the Director General of the Tax and Customs Authority. Note that this document is a copy of the document that was created in the integrated software, and should not process any recalculation or modification of the content of the integrated documents coming from other systems, respecting including the unique identification of documents (InvoiceNo, DocumentNumber or PaymentRefNo) except as mentioned in points 2.3 of the diploma", false, null),
        // T31 is not applicable because we got it already
        //new BusinessCase("T31", "If the application issues receipts, create a receipt for the document mentioned in T7 or T8 and corresponding PDF", true, PT_Phase2_CertificationExamples.Case_T31(), "T8"),
        // T32 is not supported
        // new BusinessCase("T32", "If the program allows it, create a partial receipt in the amount received (PaymentAmount) of €30.00 (in Cash VAT Regime or another that discriminates tax rates) referring to the invoice referred to in T14 with a financial discount of 10% for prompt payment and a withholding tax of 25% (note that withholdings only apply to services). If the application does not issue receipts with tax rate discrimination, but allows the issuance of another type of receipts, create a partial receipt of type (PaymentType) \"RG\". These receipts should be generated even if the application does not allow financial discounts or withholding taxes", false, null),
        // T33 is not supported
        // new BusinessCase("T33", "An example of each of all other different types of documents issued by the application and not yet provided in the previous items", true, PT_Phase2_CertificationExamples.Case_T33())
    ];
}