//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/LROE_PJ_240_1_1_FacturasEmi" +
    "tidas_ConSG_AltaPeticion_V1_0_2.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/LROE_PJ_240_1_1_FacturasEmi" +
    "tidas_ConSG_AltaPeticion_V1_0_2.xsd", IsNullable=false)]
public partial class LROEPJ240FacturasEmitidasConSGAltaPeticion {
    
    private Cabecera240Type cabeceraField;
    
    private DetalleEmitidaConSGCodificadoType[] facturasEmitidasField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Cabecera240Type Cabecera {
        get {
            return this.cabeceraField;
        }
        set {
            this.cabeceraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FacturaEmitida", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DetalleEmitidaConSGCodificadoType[] FacturasEmitidas {
        get {
            return this.facturasEmitidasField;
        }
        set {
            this.facturasEmitidasField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd")]
public partial class Cabecera240Type {
    
    private Modelo240Enum modeloField;
    
    private CapituloModelo240Enum capituloField;
    
    private SubcapituloModelo240Enum subcapituloField;
    
    private bool subcapituloFieldSpecified;
    
    private OperacionEnum operacionField;
    
    private IDVersionEnum versionField;
    
    private int ejercicioField;
    
    private NIFPersonaType obligadoTributarioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Modelo240Enum Modelo {
        get {
            return this.modeloField;
        }
        set {
            this.modeloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CapituloModelo240Enum Capitulo {
        get {
            return this.capituloField;
        }
        set {
            this.capituloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SubcapituloModelo240Enum Subcapitulo {
        get {
            return this.subcapituloField;
        }
        set {
            this.subcapituloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubcapituloSpecified {
        get {
            return this.subcapituloFieldSpecified;
        }
        set {
            this.subcapituloFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OperacionEnum Operacion {
        get {
            return this.operacionField;
        }
        set {
            this.operacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IDVersionEnum Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Ejercicio {
        get {
            return this.ejercicioField;
        }
        set {
            this.ejercicioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NIFPersonaType ObligadoTributario {
        get {
            return this.obligadoTributarioField;
        }
        set {
            this.obligadoTributarioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum Modelo240Enum {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("240")]
    Item240,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum CapituloModelo240Enum {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum SubcapituloModelo240Enum {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.1")]
    Item11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.2")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4.1")]
    Item41,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4.2")]
    Item42,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5.1")]
    Item51,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5.2")]
    Item52,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6.1")]
    Item61,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6.2")]
    Item62,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6.3")]
    Item63,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum OperacionEnum {
    
    /// <remarks/>
    A00,
    
    /// <remarks/>
    A01,
    
    /// <remarks/>
    M00,
    
    /// <remarks/>
    M01,
    
    /// <remarks/>
    AN0,
    
    /// <remarks/>
    C00,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum IDVersionEnum {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.0")]
    Item10,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd")]
public partial class NIFPersonaType {
    
    private string nIFField;
    
    private string apellidosNombreRazonSocialField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NIF {
        get {
            return this.nIFField;
        }
        set {
            this.nIFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApellidosNombreRazonSocial {
        get {
            return this.apellidosNombreRazonSocialField;
        }
        set {
            this.apellidosNombreRazonSocialField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd")]
public partial class EntidadSucedidaType {
    
    private string nombreRazonField;
    
    private string nIFField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NombreRazon {
        get {
            return this.nombreRazonField;
        }
        set {
            this.nombreRazonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NIF {
        get {
            return this.nIFField;
        }
        set {
            this.nIFField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd")]
public partial class DetalleInmuebleType {
    
    private SituacionInmuebleEnum situacionInmuebleField;
    
    private string referenciaCatastralField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SituacionInmuebleEnum SituacionInmueble {
        get {
            return this.situacionInmuebleField;
        }
        set {
            this.situacionInmuebleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReferenciaCatastral {
        get {
            return this.referenciaCatastralField;
        }
        set {
            this.referenciaCatastralField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum SituacionInmuebleEnum {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd")]
public partial class OtraInformacionTrascendenciaTributariaType {
    
    private string nIFRepresentanteDeclaradoField;
    
    private DetalleInmuebleType[] inmueblesField;
    
    private string importeTransmisionInmueblesSujetoAIVAField;
    
    private string numRegistroAcuerdoFacturacionField;
    
    private string referenciaExternaField;
    
    private SiNoEnum cuponField;
    
    private bool cuponFieldSpecified;
    
    private EntidadSucedidaType entidadSucedidaField;
    
    private SiNoEnum facturacionDispAdicionalSegundaYQuintaField;
    
    private bool facturacionDispAdicionalSegundaYQuintaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NIFRepresentanteDeclarado {
        get {
            return this.nIFRepresentanteDeclaradoField;
        }
        set {
            this.nIFRepresentanteDeclaradoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("DetalleInmueble", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public DetalleInmuebleType[] Inmuebles {
        get {
            return this.inmueblesField;
        }
        set {
            this.inmueblesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ImporteTransmisionInmueblesSujetoAIVA {
        get {
            return this.importeTransmisionInmueblesSujetoAIVAField;
        }
        set {
            this.importeTransmisionInmueblesSujetoAIVAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NumRegistroAcuerdoFacturacion {
        get {
            return this.numRegistroAcuerdoFacturacionField;
        }
        set {
            this.numRegistroAcuerdoFacturacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReferenciaExterna {
        get {
            return this.referenciaExternaField;
        }
        set {
            this.referenciaExternaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SiNoEnum Cupon {
        get {
            return this.cuponField;
        }
        set {
            this.cuponField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CuponSpecified {
        get {
            return this.cuponFieldSpecified;
        }
        set {
            this.cuponFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntidadSucedidaType EntidadSucedida {
        get {
            return this.entidadSucedidaField;
        }
        set {
            this.entidadSucedidaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SiNoEnum FacturacionDispAdicionalSegundaYQuinta {
        get {
            return this.facturacionDispAdicionalSegundaYQuintaField;
        }
        set {
            this.facturacionDispAdicionalSegundaYQuintaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FacturacionDispAdicionalSegundaYQuintaSpecified {
        get {
            return this.facturacionDispAdicionalSegundaYQuintaFieldSpecified;
        }
        set {
            this.facturacionDispAdicionalSegundaYQuintaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_Enumerados.xsd")]
public enum SiNoEnum {
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.batuz.eus/fitxategiak/batuz/LROE/esquemas/batuz_TiposComplejos.xsd")]
public partial class DetalleEmitidaConSGCodificadoType {
    
    private byte[] ticketBaiField;
    
    private OtraInformacionTrascendenciaTributariaType otraInformacionTrascendenciaTributariaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] TicketBai {
        get {
            return this.ticketBaiField;
        }
        set {
            this.ticketBaiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OtraInformacionTrascendenciaTributariaType OtraInformacionTrascendenciaTributaria {
        get {
            return this.otraInformacionTrascendenciaTributariaField;
        }
        set {
            this.otraInformacionTrascendenciaTributariaField = value;
        }
    }
}
