name: 'Build'
inputs:
  path:
    required: true
    type: string
  project:
    required: true
    type: string  

runs:
  using: "composite"
  steps:
    - name: Install MinVer
      run: dotnet tool install --global minver-cli --version 6.0.0
      shell: pwsh

    - name: Publish v1 Nuget packages
      shell: pwsh
      run: |
        $version = ""

        $csprojFile = "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.csproj"
        $nuspecFile = "${{ inputs.path }}/${{ inputs.project }}/.nuspec"

        [xml]$csprojContent = Get-Content -Path $csprojFile
        foreach ($propertyGroup in $csprojContent.Project.PropertyGroup) {
          if ($propertyGroup.MinVerTagPrefix) {
            $version = minver --verbosity error -t $($propertyGroup.MinVerTagPrefix) -p ci
            break
          }
        }

        Write-Host "Version: $version"
        if($version -eq "") {
          Write-Error "Version not found"
          exit 1
        }

        $args = ""
        if(Test-Path $nuspecFile) {
          $xml = New-Object XML
          $xml.Load($nuspecFile)
          $element =  $xml.SelectSingleNode("/package/metadata/version")
          $element.InnerText = $version
          $xml.Save($nuspecFile)

          $args += "/p:NuspecFile=.nuspec"
        }
       
        dotnet pack "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.csproj" --no-restore --configuration Release --output ./publish/package-v1-${{ inputs.project }} $args
      


    - name: Upload v1 Package
      uses: actions/upload-artifact@v4
      with:
        name: package-v1-${{ inputs.project }}
        path: ./publish/package-v1-${{ inputs.project }}

    - name: Publish v2 zip packages
      shell: pwsh
      run: |
        $version = ""

        New-Item -ItemType Directory -Force -Path ./publish/package-v2-${{ inputs.project }}
        $csprojFile = "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.csproj"

        [xml]$csprojContent = Get-Content -Path $csprojFile
        foreach ($propertyGroup in $csprojContent.Project.PropertyGroup) {
          if ($propertyGroup.MinVerTagPrefix) {
            $version = minver --verbosity error -t $($propertyGroup.MinVerTagPrefix) -p ci
            break
          }
        }

        Write-Host "Version: $version"
        if($version -eq "") {
          Write-Error "Version not found"
          exit 1
        }

        dotnet publish $csprojFile --configuration Release -f net6 --output ./publish/raw/package-v2-${{ inputs.project }} --no-build /p:DebugType=None /p:DebugSymbols=false
        Compress-Archive -Path ./publish/raw/package-v2-${{ inputs.project }}/* -DestinationPath ./publish/package-v2-${{ inputs.project }}/$version.zip

        $hash = Get-FileHash ./publish/package-v2-${{ inputs.project }}/$version.zip -Algorithm SHA256
        $hashbytes = $hash.Hash -split '([A-F0-9]{2})' | foreach-object { if ($_) {[System.Convert]::ToByte($_,16)}}
        $hashstring = [System.Convert]::ToBase64String($hashbytes)
        $hashstring | Set-Content ./publish/package-v2-${{ inputs.project }}/$version.zip.hash
        ls ./publish/package-v2-${{ inputs.project }}

    - name: Upload v2 Package
      uses: actions/upload-artifact@v4
      with:
        name: package-v2-${{ inputs.project }}
        path: ./publish/package-v2-${{ inputs.project }}