name: "Package"
inputs:
  path:
    required: true
  project:
    required: true
  targetFramework:
    required: false
    default: net6.0

outputs:
  version:
    description: "The version of the package"
    value: ${{ steps.version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Get Version
      id: version
      uses: ./.github/actions/version
      with:
        path: ${{ inputs.path }}
        project: ${{ inputs.project }}

    - name: Package V1
      uses: ./.github/actions/package-v1
      with:
        path: ${{ inputs.path }}
        project: ${{ inputs.project }}
        version: ${{ steps.version.outputs.version }}

    - name: Publish V2
      shell: pwsh
      run: |
        dotnet publish "${{ inputs.path }}/${{ inputs.project }}/${{ inputs.project }}.csproj" --configuration Release -f ${{ inputs.targetFramework }} --no-build --output ./publish/raw/package-v2-${{ inputs.project }} /p:DebugType=None /p:DebugSymbols=false

    - name: Package V2
      uses: ./.github/actions/package-v2
      with:
        artifactName: package-v2-${{ inputs.project }}
        path: ./publish/raw/package-v2-${{ inputs.project }}
        zipFileName: ${{ steps.version.outputs.version }}
        includeHash: true
