resources:
  - repo: self

trigger:
  batch: true
  branches:
    include:
      - main
      - refs/tags/storage/v*

pr:
  branches:
    include:
      - main

variables:
  - group: "Code Signing Certificates"
  - name: BuildConfiguration
    value: release
  - name: BuildPlatform
    value: any cpu
  - name: Solution
    value: "fiskaltrust.storage.sln"
  - name: vmImageName
    value: "windows-latest"

jobs:
  - job: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - powershell: |
          $nugetFeed = if ($Env:BUILD_SOURCEBRANCH.StartsWith("refs/tags/storage/v")) { "release" } else { "dev" }
          Write-Host "##vso[task.setvariable variable=NuGetFeed;]$nugetFeed"
        displayName: Set NuGet feed

      - checkout: self
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: "Use .NET 6 SDK"
        inputs:
          packageType: "sdk"
          version: "6.x"

      - task: DotNetCoreCLI@2
        inputs:
          command: "restore"
          projects: "storage/*.sln"
          vstsFeed: "$(NuGetFeed)"
          verbosityRestore: "minimal"
          arguments: "--configuration Release"
        displayName: "Restore"

      - task: DotNetCoreCLI@2
        inputs:
          command: "build"
          projects: "storage/*.sln"
          arguments: "--configuration Release"
        displayName: "Build"

      - task: DotNetCoreCLI@2
        inputs:
          command: "test"
          projects: "storage/**/*.UnitTest.csproj"
          arguments: "--configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include=[fiskaltrust.*]*"
        displayName: "Run unit tests"

      - task: SSMClientToolsSetup@1
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/storage/v')
      - task: SSMSigningToolsSetup@1
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/storage/v')

      - task: DownloadSecureFile@1
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/storage/v')
        name: clientCertificate
        displayName: "Download client certificate"
        inputs:
          secureFile: "codesigning_client_cert.p12"

      - pwsh: smctl certificate download --keypair-alias=$(KEYPAIR_ALIAS) --name=KeyCert.pem --out=$(Agent.TempDirectory)
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/storage/v')
        env:
          SM_HOST: "$(SM_HOST)"
          SM_API_KEY: "$(SM_API_KEY)"
          SM_CLIENT_CERT_PASSWORD: "$(SM_CLIENT_CERT_PASSWORD)"
          SM_CLIENT_CERT_FILE: "$(clientCertificate.secureFilePath)"
          SM_TLS_SKIP_VERIFY: false

      - pwsh: |
          Get-ChildItem -Path "$(Build.SourcesDirectory)\storage\src" -Filter *.dll -Recurse | ForEach-Object {
            signtool sign `
              /tr http://timestamp.sectigo.com/?td=sha256 `
              /td SHA256 `
              /fd SHA256 `
              /csp "DigiCert Signing Manager KSP" `
              /kc "$(KEYPAIR_ALIAS)" `
              /f $(Agent.TempDirectory)\KeyCert.pem `
              $_.FullName
          }
          Write-Host $(Get-Content -Path "~\.signingmanager\logs\smksp.log")
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/storage/v')
        env:
          SM_HOST: "$(SM_HOST)"
          SM_API_KEY: "$(SM_API_KEY)"
          SM_CLIENT_CERT_PASSWORD: "$(SM_CLIENT_CERT_PASSWORD)"
          SM_CLIENT_CERT_FILE: "$(clientCertificate.secureFilePath)"
          SM_TLS_SKIP_VERIFY: false

      - script: |
          dotnet tool install -g dotnet-reportgenerator-globaltool --version 5.3.11
          reportgenerator -reports:$(Build.SourcesDirectory)/storage/test/**/coverage.opencover.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:"Cobertura;HTMLInline;HTMLChart"
        displayName: Create Code coverage report
        workingDirectory: "/"

      - task: PublishCodeCoverageResults@1
        displayName: "Publish code coverage"
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: "$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml"
          reportDirectory: "$(Build.SourcesDirectory)/CodeCoverage"

      - script: dotnet pack storage/src/fiskaltrust.storage/fiskaltrust.storage.csproj --no-build --output $(Build.ArtifactStagingDirectory)/fiskaltrust.storage --configuration $(buildConfiguration)
        displayName: "dotnet pack storage"

      - script: dotnet pack storage/src/fiskaltrust.storage.serialization/fiskaltrust.storage.serialization.csproj --no-build --output $(Build.ArtifactStagingDirectory)/fiskaltrust.storage.serialization --configuration $(buildConfiguration)
        displayName: "dotnet pack storage serialization"

      - script: dotnet pack storage/src/fiskaltrust.storage.encryption/fiskaltrust.storage.encryption.csproj --no-build --output $(Build.ArtifactStagingDirectory)/fiskaltrust.storage.encryption --configuration $(buildConfiguration)
        displayName: "dotnet pack storage encryption"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: drop"
        inputs:
          PathtoPublish: "$(build.artifactstagingdirectory)"
