steps:
- powershell: |
    $nugetFeed = if ($Env:BUILD_SOURCEBRANCH.StartsWith("refs/heads/release/") -or $Env:BUILD_SOURCEBRANCH.StartsWith("refs/heads/main") -or $Env:BUILD_SOURCEBRANCH.StartsWith("refs/tags")) { "release" } else { "dev" }
    Write-Host "##vso[task.setvariable variable=NuGetFeed;]$nugetFeed"
  displayName: Set NuGet feed
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(WorkingDirectory)/**/fiskaltrust.Middleware.Queue.SQLite.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(NuGetFeed)'
  displayName: 'Restore'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(WorkingDirectory)/**/fiskaltrust.Middleware.Queue.SQLite.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- script: |
    dotnet publish --configuration $(buildConfiguration) --no-restore -f net461
    dotnet publish --configuration $(buildConfiguration) --no-restore -f netstandard2.0
    dotnet publish --configuration $(buildConfiguration) --no-restore -f netstandard2.1
  displayName: 'dotnet publish fiskaltrust.Middleware.Queue.SQLite'
  workingDirectory: '$(WorkingDirectory)/src/fiskaltrust.Middleware.Queue.SQLite'

- script: dotnet pack --output $(Build.ArtifactStagingDirectory) --no-restore --configuration $(buildConfiguration) /p:NuspecFile=.nuspec
  displayName: 'dotnet pack fiskaltrust.Middleware.Queue.SQLite'
  workingDirectory: '$(WorkingDirectory)/src/fiskaltrust.Middleware.Queue.SQLite'

- pwsh: |
    $sqlitePackageName="fiskaltrust.Middleware.Queue.SQLite.1.3.0-local.nupkg" 
    nuget add $(Build.ArtifactStagingDirectory)/$sqlitePackageName -Source .\test\localfeed     
  displayName: 'create localfeed'
  continueOnError: true  

- task: JavaToolInstaller@0
  inputs:
    versionSpec: "11"
    jdkArchitectureOption: "x64"
    jdkSourceOption: "PreInstalled"

- task: NuGetCommand@2
  inputs:
     command: "restore"
     arguments: "-Verbosity detailed"
     restoreSolution: 'test/**/fiskaltrust.NuspecTest.sln'
     feedsToUse: 'config'
     nugetConfigPath: "test/NuGet.config" 
  displayName: Restore NuGet packages

- task: XamarinAndroid@1
  inputs:
    projectFile: "test/**/fiskaltrust.Middleware.Queue.Sqlite.NuspecTest.csproj"
    outputDirectory: $(build.binariesDirectory)/$(buildConfiguration)
    configuration: "$(buildConfiguration)"
    msbuildVersionOption: "latest"
    jdkOption: "JDKVersion"
  displayName: Build AndriodTest Launcher
