name: 'Deploy Nuget'

inputs:
  directory:
    required: true
    type: string
  feed:
    required: true
    type: string
  pat:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name:
      shell: pwsh
      run: dotnet nuget push "${{ inputs.directory }}/*.nuget" -p "${{ inputs.pat }}" -s "${{ inputs.feed }}" -k az
      env:
        VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint":"${{ inputs.feed }}", "password":"${{ inputs.pat }}"}]'