name: 'Deploy Nuget'

inputs:
  directory:
    required: true
    type: string
  feed:
    required: true
    type: string
  apiKey:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name:
      shell: pwsh
      run: dotnet nuget push "${{ inputs.directory }}/*.nuget" -k "${{ inputs.apiKey }}" -s "${{ inputs.feed }}"