name: Command Package
on:
  repository_dispatch:
    types: [package-command, deploy-command]

permissions:
  pull-requests: write
  checks: write
  id-token: write
  contents: read

jobs:
  queue-package:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'queue'
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      pattern: fiskaltrust.Middleware.Queue.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      directory: queue/src
      commit: ${{ github.event.client_payload.pull_request.head.sha }}

  scu-at-package:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'scu-at'
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      pattern: fiskaltrust.Middleware.SCU.AT.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      directory: scu-at/src
      commit: ${{ github.event.client_payload.pull_request.head.sha }}

  scu-de-package:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'scu-de'
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      pattern: fiskaltrust.Middleware.SCU.DE.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      directory: scu-de/src
      commit: ${{ github.event.client_payload.pull_request.head.sha }}

  scu-es-package:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'scu-es'
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      pattern: fiskaltrust.Middleware.SCU.ES.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      directory: scu-es/src
      commit: ${{ github.event.client_payload.pull_request.head.sha }}

  scu-it-package:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'scu-it'
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      pattern: fiskaltrust.Middleware.SCU.IT.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      directory: scu-it/src
      commit: ${{ github.event.client_payload.pull_request.head.sha }}
       
  add-approval-link:
    needs:
      - queue-package
      - scu-at-package
      - scu-de-package
      - scu-es-package
      - scu-it-package
    runs-on: ubuntu-latest
    if: (!failure()) && github.event.client_payload.slash_command.command == 'deploy'
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: confused
          reactions-edit-mode: replace
          edit-mode: replace
          body: |
            /${{ github.event.client_payload.slash_command.command }} ${{ github.event.client_payload.slash_command.args.all }}
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/approve/yellow)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
    
  queue-deploy:
    if: (!failure()) && github.event.client_payload.slash_command.command == 'deploy'
    needs:
      - queue-package
      - scu-at-package
      - scu-de-package
      - scu-es-package
      - scu-it-package
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      package: fiskaltrust.Middleware.Queue.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      environment: sandbox

  success:
    needs:
      - queue-package
      - scu-at-package
      - scu-de-package
      - scu-es-package
      - scu-it-package
    runs-on: ubuntu-latest
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled') &&
      contains(needs.*.result, 'success')
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
          reactions-edit-mode: replace
          edit-mode: replace
          body: |
            /${{ github.event.client_payload.slash_command.command }} ${{ github.event.client_payload.slash_command.args.all }}
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/success/green)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
    
  failure:
    needs:
      - queue-package
      - queue-deploy
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: confused
          reactions-edit-mode: replace
          edit-mode: replace
          body: |
            /${{ github.event.client_payload.slash_command.command }} ${{ github.event.client_payload.slash_command.args.all }}
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/failure/red)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
