name: Package Command
on:
  repository_dispatch:
    types: [package-command]

jobs:
  queue:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'queue'
    uses: ./.github/workflows/queue-package.yml
    secrets: inherit
    with:
      package: queue/src/fiskaltrust.Middleware.Queue.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      ref: ${{ github.event.client_payload.pull_request.head.ref }}

  success:
    needs:
      - queue
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray

  failure:
    needs:
      - queue
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: confused