name: Package Command
on:
  repository_dispatch:
    types: [package-command, deploy-command]

permissions:
  pull-requests: write
  checks: write

jobs:
  queue-package:
    if: github.event.client_payload.slash_command.args.unnamed.arg1 == 'queue'
    uses: ./.github/workflows/queue-package.yml
    secrets: inherit
    with:
      package: fiskaltrust.Middleware.Queue.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      commit: ${{ github.event.client_payload.pull_request.head.sha }}

  queue-deploy:
    if: success() && github.event.client_payload.slash_command.command == 'deploy'
    needs: [queue-package]
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      package: fiskaltrust.Middleware.Queue.${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}
      environment: sandbox

  success:
    needs:
      - queue-package
      - queue-deploy
    runs-on: ubuntu-latest
    if: (!failure()) && success('queue-package')
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
          reactions-edit-mode: replace

  failure:
    needs:
      - queue-package
      - queue-deploy
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: confused
          reactions-edit-mode: replace
          body: |
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/failed/red)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
