name: Command Package
on:
  repository_dispatch:
    types: [package-command, deploy-command]

permissions:
  pull-requests: write
  checks: write
  id-token: write
  contents: read

jobs:
  meta:
    needs: []
    runs-on: windows-latest
    outputs:
      project: ${{ steps.meta.outputs.project }}
      package: ${{ steps.meta.outputs.package }}
      directory: ${{ steps.meta.outputs.directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.pull_request.head.sha }}

      - id: meta
        shell: pwsh
        run: |
          $directory = "${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}"
          $package = "${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}"
          Write-Output "package=$package"
          Write-Output "package=$package" >> $env:GITHUB_OUTPUT
          Write-Output "directory=$directory/src"
          Write-Output "directory=$directory/src" >> $env:GITHUB_OUTPUT
          $prefix = ""
          if($directory -eq "queue") {
            $prefix = "fiskaltrust.Middleware.Queue"
          } elseif($directory -match "scu-([a-z]{2})") {
            $prefix = "fiskaltrust.Middleware.SCU.$($matches[1].ToUpper())"
          }
          $project = $(Get-Item "$directory/src/$prefix.$package").Name
          Write-Output "project=$project"
          Write-Output "project=$project" >> $env:GITHUB_OUTPUT

  package:
    needs: [meta]
    uses: ./.github/workflows/package.yml
    secrets: inherit
    with:
      pattern: ${{ needs.meta.outputs.project }}
      directory: ${{ needs.meta.outputs.directory }}
      commit: ${{ github.event.client_payload.pull_request.head.sha }}
       
  add-approval-link:
    needs:
      - package
    runs-on: ubuntu-latest
    if: (!failure()) && github.event.client_payload.slash_command.command == 'deploy'
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: confused
          reactions-edit-mode: replace
          edit-mode: replace
          body: |
            /${{ github.event.client_payload.slash_command.command }} ${{ github.event.client_payload.slash_command.args.all }}
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/approve/yellow)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
    
  deploy:
    if: (!always())
    # if: (!failure()) && github.event.client_payload.slash_command.command == 'deploy'
    needs:
      - meta
      - package
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      package: ${{ needs.meta.outputs.project }}
      environment: sandbox

  success:
    needs:
      - package
      - deploy
    runs-on: ubuntu-latest
    if: success('package') && !failure('deploy')
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
          reactions-edit-mode: replace
          edit-mode: replace
          body: |
            /${{ github.event.client_payload.slash_command.command }} ${{ github.event.client_payload.slash_command.args.all }}
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/success/green)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
    
  failure:
    needs:
      - package
      - deploy
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: confused
          reactions-edit-mode: replace
          edit-mode: replace
          body: |
            /${{ github.event.client_payload.slash_command.command }} ${{ github.event.client_payload.slash_command.args.all }}
            [![](https://badgen.net/static/${{ github.event.client_payload.slash_command.command }}%20${{ github.run_id }}/failure/red)](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
