name: Deploy

on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  nuget:
    name: Deploy Nuget Feed
    runs-on: windows-latest
    needs: []
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Download v1 Package
        uses: actions/download-artifact@v4
        with:
          name: package-v1-${{ inputs.package }}
          path: artifacts
      
      - name: Deploy to Nuget Feed
        uses: ./.github/actions/deploy-nuget
        with:
          feed: ${{ vars.NUGET_FEED_URL }}
          path: artifacts/package-v1-${{ inputs.package }}
          apiKey: ${{ secrets.NUGET_FEED_API_KEY }}

  packages-v1:
    name: Deploy v1 Packages
    runs-on: ubuntu-latest
    needs: []
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Download v1 Package
        uses: actions/download-artifact@v4
        with:
          name: package-v1-${{ inputs.package }}
          path: artifacts

      - name: Deploy to v1 Packages
        uses: ./.github/actions/deploy-v1-packages
        with:
          directory: artifacts/package-v2-${{ inputs.package }}
          package: ${{ inputs.package }}
          storageAccountName: ${{ vars.PACKAGES_V1_STORAGE_ACCOUNT_NAME }}
          sas: ${{ secrets.PACKAGES_V1_STORAGE_ACCOUNT_SAS }}

  packages-v2:
    name: Deploy v2 Package
    runs-on: ubuntu-latest
    needs: []
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Download v2 Package
        uses: actions/download-artifact@v4
        with:
          name: package-v2-${{ inputs.package }}
          path: artifacts

      - name: Deploy to v2 Packages
        uses: ./.github/actions/deploy-v2-packages
        with:
          directory: artifacts/package-v2-${{ inputs.package }}
          package: ${{ inputs.package }}
          storageAccountName: ${{ secrets.PACKAGES_V2_STORAGE_ACCOUNT_NAME }}
          sas: ${{ secrets.PACKAGES_V2_STORAGE_ACCOUNT_SAS }}
