name: Summary
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited
      - ready_for_review
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
jobs:
  enforce-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@7edf5f0713401872da70b3a69eac93ed16edc97b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delay: 30
