name: Queue CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      commit:
        type: string
        required: false
  pull_request:
    paths:
      - .github/workflows/**
      - queue/**

jobs:
  test:
    name: Test
    runs-on:  windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
          fetch-depth: 0

      - uses: ./.github/actions/build
        with:
          pattern: queue/fiskaltrust.Middleware.sln
          configuration: Debug

      - name: Unit Tests
        uses: ./.github/actions/test
        with:
          directory: queue/test
          pattern: "UnitTest"
          args: '--no-build --filter only!=local'
        env:
          CONNECTIONSTRING_AZURE_STORAGE_TESTS: ${{ secrets.CONNECTIONSTRING_AZURE_STORAGE_TESTS }}
          CONNECTIONSTRING_MYSQL_TESTS: ${{ secrets.CONNECTIONSTRING_MYSQL_TESTS }}

      - name: Integration Tests
        uses: ./.github/actions/test
        with:
          directory: queue/test
          pattern: "IntegrationTest"
          args: '--no-build --filter only!=local'
        env:
          CONNECTIONSTRING_AZURE_STORAGE_TESTS: ${{ secrets.CONNECTIONSTRING_AZURE_STORAGE_TESTS }}
          CONNECTIONSTRING_MYSQL_TESTS: ${{ secrets.CONNECTIONSTRING_MYSQL_TESTS }}

  publish-test-results:
    name: Publish Tests Results
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Queue Test Results
          comment_mode: always
          files: "artifacts/**/*.trx"
          commit: ${{ inputs.commit }}