name: Queue Package

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        options:
          - fiskaltrust.Middleware.Queue.AzureTableStorage
          - fiskaltrust.Middleware.Queue.EF
          - fiskaltrust.Middleware.Queue.InMemory
          - fiskaltrust.Middleware.Queue.MySQL
          - fiskaltrust.Middleware.Queue.PostgreSQL
          - fiskaltrust.Middleware.Queue.SQLite
      deploy:
        type: boolean
        default: false

  workflow_call:
    inputs:
      package:
        type: string
        required: true
      commit:
        type: string
        required: false

jobs:
  package:
    name: Package
    runs-on:  windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
          ref: ${{ inputs.commit }}

      - uses: ./.github/actions/build
        with:
          solution: queue/fiskaltrust.Middleware.sln

      # - run: |
      #     dotnet publish --configuration Release --no-restore -f net461
      #     dotnet publish --configuration Release --no-restore -f netstandard2.0
      #     dotnet publish --configuration Release --no-restore -f netstandard2.1
      #   if: inputs.package == 'fiskaltrust.Middleware.Queue.SQLite'
      #   working-directory: queue/src/fiskaltrust.Middleware.Queue.SQLite
      #   name: Publish SQLite for nuget

      - uses: ./.github/actions/sign
        with:
          path: queue/src
          certificate: '${{ secrets.SIGNING_CERTIFICATE }}'
          password: '${{ secrets.SIGNING_CERT_PASSWORD }}'

      - uses: ./.github/actions/package
        with:
          path: queue/src
          project: ${{ inputs.package }}
  
  deploy:
    if: inputs.deploy
    needs: [package]
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy.yml
    with:
      package: ${{ inputs.package }}
      environment: sandbox