name: Queue Acceptance Tests

on:
  workflow_dispatch:
    inputs:
      only:
        type: choice
        options:
          - ' '
          - fiskaltrust.Middleware.Storage.AzureTableStorage.AcceptanceTest
          - fiskaltrust.Middleware.Storage.EF.AcceptanceTest
          - fiskaltrust.Middleware.Storage.SQLite.AcceptanceTest
          - fiskaltrust.Middleware.Storage.MySQL.AcceptanceTest
          - fiskaltrust.Middleware.Storage.InMemory.AcceptanceTest
        required: false
  workflow_call:
    inputs:
      commit:
        type: string
        required: false
      only:
        type: string
        required: false
  push:
    branches:
      - main
    tags-ignore:
      - '*/**/v*'
    paths:
      - 'queue/**'

concurrency:
  group: queue-acceptance-tests

jobs:
  storage-acceptance-test:
    name: Acceptance Tests
    runs-on: windows-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        project:
          - fiskaltrust.Middleware.Storage.AzureTableStorage.AcceptanceTest
          - fiskaltrust.Middleware.Storage.EF.AcceptanceTest
          - fiskaltrust.Middleware.Storage.SQLite.AcceptanceTest
          - fiskaltrust.Middleware.Storage.MySQL.AcceptanceTest
          - fiskaltrust.Middleware.Storage.InMemory.AcceptanceTest
    steps:
      - uses: actions/setup-dotnet@v4
        with:
         dotnet-version: |
          6.0.x
          8.0.x

      - uses: actions/checkout@v4
        if: inputs.only == '' || inputs.only == ' ' || inputs.only == matrix.project
        with:
          ref: ${{ inputs.commit }}

      - name: ${{ matrix.project }} Acceptance Tests
        if: inputs.only == '' || inputs.only == ' ' || inputs.only == matrix.project
        uses: ./.github/actions/test
        with:
          directory: queue/test
          pattern: ${{ matrix.project }}
        env:
          CONNECTIONSTRING_AZURE_STORAGE_TESTS: ${{ secrets.CONNECTIONSTRING_AZURE_STORAGE_TESTS }}
          CONNECTIONSTRING_MYSQL_TESTS: ${{ secrets.CONNECTIONSTRING_MYSQL_TESTS }}

  queue-acceptance-test:
    name: Acceptance Tests
    runs-on: windows-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        project:
          - fiskaltrust.Middleware.QueueSynchronizer.AcceptanceTest
          - fiskaltrust.Middleware.Queue.AcceptanceTest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}

      - name: ${{ matrix.project }} Acceptance Tests
        uses: ./.github/actions/test
        with:
          directory: queue/test
          pattern: ${{ matrix.project }}

  publish-test-results:
    name: Publish Tests Results
    needs: [ queue-acceptance-test, storage-acceptance-test ]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Acceptance Test Results
          comment_mode: always
          files: "artifacts/**/*.trx"
          commit: ${{ inputs.commit }}