name: SCU.AT Package

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        options:
          - fiskaltrust.Middleware.SCU.AT.ATrustSmartcard
          - fiskaltrust.Middleware.SCU.AT.InMemory
          - fiskaltrust.Middleware.SCU.AT.PrimeSignHSM
      deploySandbox:
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  package:
    secrets: inherit
    uses: ./.github/workflows/package.yml
    with:
      pattern: ${{ inputs.package }}
      directory: scu-at/src
      deploySandbox: ${{ inputs.deploySandbox}}