name: SCU.DE CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      commit:
        type: string
        required: false
  pull_request:
    paths:
      - .github/workflows/**
      - scu-de/**

jobs:
  test:
    name: Test
    runs-on:  windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}
          fetch-depth: 0
          filter: tree:0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
    
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Set default Xamarin SDK versions
        run: |
          $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=13

      - uses: ./.github/actions/build
        with:
          pattern: scu-de/fiskaltrust.Middleware.SCU.DE.sln
          configuration: Debug
          xamarin: true

      - name: Unit Tests
        uses: ./.github/actions/test
        with:
          directory: scu-de/test
          pattern: "UnitTest"
          args: '--no-build'

      - name: Integration Tests
        uses: ./.github/actions/test
        with:
          directory: scu-de/test
          pattern: "IntegrationTest"
          args: '--no-build'

      - name: Acceptance Tests
        uses: ./.github/actions/test
        with:
          directory: scu-de/test
          pattern: "AcceptanceTests"
          args: '--no-build'

  publish-test-results:
    name: Publish Tests Results
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: SCU.DE Test Results
          comment_mode: always
          files: "artifacts/**/*.trx"
          commit: ${{ inputs.commit }}