name: SCU.IT Package

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        options:
          - fiskaltrust.Middleware.SCU.IT.CustomRTPrinter
          - fiskaltrust.Middleware.SCU.IT.CustomRTServer
          - fiskaltrust.Middleware.SCU.IT.EpsonRTPrinter
      deploySandbox:
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  package:
    secrets: inherit
    uses: ./.github/workflows/package.yml
    with:
      pattern: ${{ inputs.package }}
      directory: scu-it/src
      deploySandbox: ${{ inputs.deploySandbox}}