name: Setup Windows SQL Server

on:
  workflow_call:

jobs:
  sqlserver:
    runs-on: windows-latest
    outputs:
      sql-host: ${{ steps.set-host.outputs.sql-host }}
      sql-port: "1433"
      sa-password: ${{ steps.set-host.outputs.sa-password }}

    steps:
      - name: Pull SQL Server Docker image
        run: docker pull mcr.microsoft.com/mssql/server:2022-latest-windows

      - name: Run SQL Server container
        run: |
          docker run -d --name sqlserver `
            -e "ACCEPT_EULA=Y" `
            -e "SA_PASSWORD=YourStrong!Passw0rd" `
            -p 1433:1433 `
            mcr.microsoft.com/mssql/server:2022-latest-windows

      - name: Wait for SQL Server
        shell: pwsh
        run: |
          $maxRetries = 30
          $i = 0
          while ($i -lt $maxRetries) {
              try {
                  docker exec sqlserver powershell -Command "Invoke-Sqlcmd -Query 'SELECT 1;' -ServerInstance localhost -Username sa -Password 'YourStrong!Passw0rd'"
                  Write-Host "SQL Server is ready!"
                  break
              } catch {
                  Write-Host "Waiting for SQL Server..."
                  Start-Sleep -Seconds 5
                  $i++
              }
          }

      - name: Set SQL outputs
        id: set-host
        run: |
          echo "::set-output name=sql-host::localhost"
          echo "::set-output name=sa-password::YourStrong!Passw0rd"
