resources:
  - repo: self

trigger:
  batch: true
  branches:
    include:
      - main
      - refs/tags/scu-es/*
  paths:
    include:
      - scu-es

pr:
  branches:
    include:
      - main
      - refs/tags/scu-es/*
  paths:
    include:
      - scu-es

variables:
  - group: "Code Signing Certificates"
  - name: BuildConfiguration
    value: release
  - name: Solution
    value: "fiskaltrust.Middleware.SCU.ES.sln"
  - name: vmImageName
    value: "windows-2022"
  - name: WorkingDirectory
    value: "scu-es"

stages:
  - stage: Test
    jobs:
      - job: Test
        displayName: Unit and integration tests
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: templates/scu-es/test.template.yml

  - stage: Build
    dependsOn: Test
    jobs:
      - job: BuildNugetPackages
        displayName: Build v1 NuGet packages
        dependsOn: []
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: templates/scu-es/build-nuget.template.yml

      - job: BuildZipPackages
        displayName: Build v2 zip packages
        dependsOn: []
        pool:
          vmImage: $(vmImageName)
        steps:
          - template: templates/build-zip.yml
            parameters:
              workingDirectory: scu-es
              projects:
                - fiskaltrust.Middleware.SCU.ES.TicketBAI
