resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - main
    - refs/tags/scu-at/*
  paths:
    include:
      - scu-at

pr:
  branches:
    include:
    - main
    - refs/tags/scu-at/*
  paths:
    include:
      - scu-at

variables:
- group: 'Code Signing Certificates'
- name: BuildConfiguration
  value: release
- name: Solution
  value: 'fiskaltrust.Middleware.SCU.AT.sln'
- name: vmImageName 
  value: 'windows-2022'
- name: WorkingDirectory
  value: 'scu-at'

stages:
  - stage: Test
    jobs:
    - job: Test
      displayName: Unit and integration tests
      pool:
        vmImage: $(vmImageName)
      steps:
      - template: templates/scu-at/test.template.yml

  - stage: Build
    dependsOn: Test
    jobs:
    - job: BuildNugetPackages
      displayName: Build v1 NuGet packages
      condition: succeeded()
      pool:
        vmImage: $(vmImageName)
      steps:
      - template: templates/scu-at/build-nuget.template.yml

    - job: BuildZipPackages
      displayName: Build v2 zip packages
      condition: succeeded()
      pool:
        vmImage: $(vmImageName)
      steps:
      - template: templates/build-zip.yml
        parameters:
          workingDirectory: scu-at
          projects:
            - fiskaltrust.Middleware.SCU.AT.ATrustSmartcard
            - fiskaltrust.Middleware.SCU.AT.InMemory