resources:
  pipelines:
    - pipeline: build
      source: fiskaltrust.Middleware.Queue
      trigger:
        branches:
          include:
            - refs/tags/queue/*

trigger: none
pr: none

stages:
  - template: templates/release.yml
    parameters:
      type: fiskaltrust.Middleware.Queue
      artifact: build
      projects:
        - InMemory
        - SQLite
        - EF
        - MySQL
        - PostgreSQL
      stages:
        - stage: Release_Sandbox
          dependsOn: []
          templateContext:
            environment: sandbox
            storage: stdevwesteuropepackages
            serviceConnection: rg-dev-westeurope-packages

        - stage: Release_Production
          templateContext:
            dependsOnPrefix: Release_Sandbox
            environment: production
            storage: stprodwesteuropepackages
            serviceConnection: rg-prod-westeurope-packages

  - template: templates/release-legacy.yml
    parameters:
      type: fiskaltrust.Middleware.Queue
      artifact: build
      projects:
        - InMemory
        - SQLite
        - EF
        - MySQL
        - PostgreSQL
      stages:
        - stage: Release_Sandbox_Legacy
          dependsOn: []
          templateContext:
            environment: sandbox-legacy
            storage: fiskaltrustsandbox
            serviceConnection: sandbox-legacy-packages

        - stage: Release_Production_Legacy
          templateContext:
            dependsOnPrefix: Release_Sandbox_Legacy
            environment: production-legacy
            storage: fiskaltrustcommonwe1
            serviceConnection: production-legacy-packages

  - template: templates/release-legacy-nuget.yml
    parameters:
      type: fiskaltrust.Middleware.Queue
      artifact: build
      projects:
        - InMemory
        - SQLite
        - EF
        - MySQL
        - PostgreSQL
      stages:
        - stage: Release_Sandbox_Legacy_Nuget
          dependsOn: []
          templateContext:
            environment: sandbox-legacy-nuget
            feed: dev
            serviceConnection: sandbox-legacy-packages

        - stage: Release_Production_Legacy_Nuget
          templateContext:
            dependsOnPrefix: Release_Sandbox_Legacy_Nuget
            environment: production-legacy-nuget
            feed: middleware
            serviceConnection: production-legacy-packages